apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi
  name: multi
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - echo hello1; sleep 3600
    image: busybox
    name: multi-1
    resources: {}
  - command:
    - /bin/sh
    - -c
    - echo hello2; sleep 3600
    image: busybox
    name: multi-2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
