apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-3
  name: busybox-3
spec:
  containers:
  - command:
    - env
    image: busybox
    name: busybox-3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
